# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='pago',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
